/*
 * Copyright (C) 2025 InterChat
 *
 * InterChat is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * InterChat is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with InterChat.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Content filter configuration for InterChat calls
 * This file contains lists of prohibited terms organized by category
 */


/**
 * Prohibited terms for InterChat calls
 */
export const prohibitedContent: string[] = [
  '2g1c',
  '2 girls 1 cup',
  'acrotomophilia',
  'alabama hot pocket',
  'alaskan pipeline',
  'anal',
  'anilingus',
  'anus',
  'baby juice',
  'ball gag',
  'ball kicking',
  'ball licking',
  'ball sack',
  'ball sucking',
  'bangbros',
  'bangbus',
  'bareback',
  'barenaked',
  'bbw',
  'bdsm',
  'beaner',
  'beaners',
  'beaver cleaver',
  'beaver lips',
  'beastiality',
  'bestiality',
  'bimbos',
  'birdlock',
  'bitch',
  'bitches',
  'blonde action',
  'blonde on blonde action',
  'blowjob',
  'blow job',
  'blow your load',
  'blumpkin',
  'bollocks',
  'bondage',
  'boner',
  'brunette action',
  'bukkake',
  'bulldyke',
  'bullet vibe',
  'bung hole',
  'bunghole',
  'busty',
  'butt',
  'buttcheeks',
  'butthole',
  'camel toe',
  'camgirl',
  'camslut',
  'camwhore',
  'carpet muncher',
  'carpetmuncher',
  'chocolate rosebuds',
  'cialis',
  'circlejerk',
  'cleveland steamer',
  'clit',
  'clitoris',
  'clover clamps',
  'cock',
  'cocks',
  'coprolagnia',
  'coprophilia',
  'cornhole',
  'coon',
  'coons',
  'creampie',
  'cum',
  'cumming',
  'cumshot',
  'cumshots',
  'cunnilingus',
  'cunt',
  'darkie',
  'date rape',
  'daterape',
  'deep throat',
  'deepthroat',
  'dendrophilia',
  'dick',
  'dildo',
  'dingleberry',
  'dingleberries',
  'dirty pillows',
  'dirty sanchez',
  'doggie style',
  'doggiestyle',
  'doggy style',
  'doggystyle',
  'dog style',
  'dolcett',
  'domination',
  'dominatrix',
  'dommes',
  'donkey punch',
  'double dong',
  'double penetration',
  'dp action',
  'dry hump',
  'dvda',
  'ecchi',
  'ejaculation',
  'erotic',
  'erotism',
  'escort',
  'eunuch',
  'fag',
  'faggot',
  'fecal',
  'felch',
  'fellatio',
  'feltch',
  'female squirting',
  'femdom',
  'figging',
  'fingerbang',
  'fingering',
  'fisting',
  'foot fetish',
  'footjob',
  'frotting',
  'fudge packer',
  'fudgepacker',
  'futanari',
  'gangbang',
  'gang bang',
  'gay sex',
  'genitals',
  'giant cock',
  'goatcx',
  'goatse',
  'god damn',
  'gokkun',
  'goregasm',
  'grope',
  'group sex',
  'g-spot',
  'guro',
  'hand job',
  'handjob',
  'hard core',
  'hardcore',
  'hentai',
  'homoerotic',
  'honkey',
  'hooker',
  'horny',
  'hot carl',
  'hot chick',
  'how to kill',
  'how to murder',
  'huge fat',
  'humping',
  'incest',
  'intercourse',
  'jack off',
  'jail bait',
  'jailbait',
  'jelly donut',
  'jerk off',
  'jigaboo',
  'jiggaboo',
  'jiggerboo',
  'jizz',
  'juggs',
  'kike',
  'kinbaku',
  'kinkster',
  'kinky',
  'knobbing',
  'lemon party',
  'livesex',
  'lolita',
  'lovemaking',
  'make me come',
  'male squirting',
  'masturbate',
  'masturbating',
  'masturbation',
  'menage a trois',
  'milf',
  'missionary position',
  'mong',
  'mound of venus',
  'muff diver',
  'muffdiving',
  'nambla',
  'nawashi',
  'negro',
  'neonazi',
  'nig',
  'nigga',
  'nigger',
  'nig nog',
  'nimphomania',
  'nipple',
  'nipples',
  'nsfw',
  'nude',
  'nudity',
  'nutten',
  'nympho',
  'nymphomania',
  'octopussy',
  'omorashi',
  'one cup two girls',
  'one guy one jar',
  'orgasm',
  'orgy',
  'paedophile',
  'paki',
  'panties',
  'panty',
  'pedobear',
  'pedophile',
  'pegging',
  'penis',
  'phone sex',
  'pikey',
  'piss pig',
  'pisspig',
  'pleasure chest',
  'pole smoker',
  'ponyplay',
  'poof',
  'poon',
  'poontang',
  'punany',
  'poop chute',
  'poopchute',
  'porn',
  'porno',
  'pornography',
  'prince albert piercing',
  'pthc',
  'pubes',
  'pussy',
  'queaf',
  'queef',
  'quim',
  'raghead',
  'raging boner',
  'rape',
  'raping',
  'rapist',
  'rectum',
  'reverse cowgirl',
  'rimjob',
  'rimming',
  'rosy palm',
  'rosy palm and her 5 sisters',
  'sadism',
  'santorum',
  'scat',
  'schlong',
  'scissoring',
  'semen',
  'sex',
  'sexcam',
  'sexo',
  'sexy',
  'sexual',
  'sexually',
  'shaved beaver',
  'shaved pussy',
  'shemale',
  'shibari',
  'shrimping',
  'skeet',
  'slanteye',
  'slut',
  's&m',
  'smut',
  'snatch',
  'snowballing',
  'sodomize',
  'sodomy',
  'spastic',
  'splooge',
  'splooge moose',
  'spooge',
  'spread legs',
  'strap on',
  'strapon',
  'strappado',
  'strip club',
  'style doggy',
  'swinger',
  'threesome',
  'throating',
  'thumbzilla',
  'titty',
  'topless',
  'tosser',
  'towelhead',
  'tranny',
  'tribadism',
  'tub girl',
  'tubgirl',
  'tushy',
  'twat',
  'two girls one cup',
  'undressing',
  'urethra play',
  'urophilia',
  'vagina',
  'viagra',
  'vibrator',
  'vorarephilia',
  'voyuer',
  'vulva',
  'wank',
  'white power',
  'zoophilia',
  'yiffy',
  'chink',
  'chinky',
];

/**
 * Humorous responses to display when a message is blocked
 */
export const blockedMessageResponses = [
  'Oops! Looks like their message was a bit too spicy for our taste. 🌶️',
  'Their message got sent to timeout for bad behavior. 🤫',
  'Our filter caught something naughty in their message. 👀',
  'They tried to send a message, but it tripped and fell into our filter. 🏃‍♂️',
  'Their message didn’t pass the vibe check. ✋',
];

/**
 * Get a random humorous response for blocked messages
 * @returns A random response from the blockedMessageResponses array
 */
export function getRandomBlockedMessageResponse(): string {
  const randomIndex = Math.floor(Math.random() * blockedMessageResponses.length);
  return blockedMessageResponses[randomIndex];
}
